tap "homebrew/bundle"
tap "smudge/smudge"
brew "bat"
brew "dockutil"
brew "fd"
brew "fzf"
brew "grc"
brew "gh"
brew "git"
brew "git-delta"
brew "gnupg"
brew "go"
brew "mas"
brew "nightlight"
brew "node"
brew "ripgrep"
brew "rmtrash"
cask "1password"
cask "chatgpt"
cask "cursor"
cask "discord"
cask "gather"
cask "ghostty"
cask "google-chrome"
cask "karabiner-elements"
cask "notion"
cask "notion-calendar"
cask "ollama"
cask "orbstack"
cask "spotify"
cask "superhuman"
cask "zoom"
mas "1Password for Safari", id: 1569813296
mas "Slack", id: 803453959
mas "Tailscale", id: 1475387142
mas "Yubico Authenticator", id: 1497506650
