tap "homebrew/bundle"
tap "smudge/smudge"
brew "bat"
brew "dockutil"
brew "fd"
brew "fzf"
brew "grc"
brew "gh"
brew "git"
brew "git-delta"
brew "gnupg"
brew "go"
brew "htop"
brew "jq"
brew "mas"
brew "mtr"
brew "nightlight"
brew "nmap"
brew "node"
brew "pure"
brew "ripgrep"
brew "watch"
brew "wget"
brew "rmtrash"
brew "tailscale"
brew "yq"
brew "zoxide"
cask "1password"
cask "chatgpt"
cask "cursor"
cask "discord"
cask "gather"
cask "ghostty"
cask "google-chrome"
cask "karabiner-elements"
cask "notion"
cask "notion-calendar"
cask "orbstack"
cask "spotify"
cask "superhuman"
cask "zed"
cask "zoom"
mas "1Password for Safari", id: 1569813296
mas "Slack", id: 803453959
mas "Tailscale", id: 1475387142
mas "Yubico Authenticator", id: 1497506650
